apiVersion: v1
kind: Secret
metadata:
  name: "test-secret-1"
type: Opaque
data:
  {{- include "getValueFromSecret" . | indent 2}}
---

{{- if (lookup "v1" "Secret" "default" "secret24") }}
apiVersion: v1
kind: Secret
metadata:
  name: "test-secret"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" "default" "secret24") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $Secret := (get $secretData "secretkey") | default "NotFound" }}
  {{- $Access := (get $secretData "accesskey") | default "NotFound" }}
  AccessKey: {{ $Access | quote }}
  SecretKey: {{ $Secret | quote }}
{{- end}}
